// Generated by scripts/twa-build.mjs — run `npm run twa:apk` to refresh.
export const androidApp = {
  "host": "pediu.grok.me",
  "startPath": "/",
  "packageId": "me.grok.pediu",
  "version": "1.0.0",
  "file": "/download/pediu.apk",
  "bytes": 1773679,
  "fingerprint": "CB:BE:02:A9:3C:FD:29:14:A7:97:C4:48:55:31:22:2B:50:57:B7:10:C7:9C:6F:4F:1F:E2:11:E4:11:3F:76:FF",
  "builtAt": "2026-10-04"
} as const;
